minecraft_version=1.21
minecraft_dependency=~1.21
archive_minecraft_version=1.21
modrinth_game_version=1.21
version_aliases=1.21.0
java_version=21
loom_mode=remap
fabric_api_version=0.102.0+1.21
modmenu_version=17.0.0
overlay_from=1.21.5
