minecraft_version=26.1.1
minecraft_dependency=26.1.1
java_version=25
java_dependency=>=25
mixin_compatibility_level=JAVA_25
loom_mode=named
fabric_api_version=0.145.3+26.1.1
modmenu_version=18.0.0-alpha.8
overlay_from=26.1
