// Secrets set via `wrangler secret put` — not generated by `wrangler types`
declare namespace Cloudflare {
	interface Env {
		R2_ACCESS_KEY_ID: string;
		R2_SECRET_ACCESS_KEY: string;
		R2_ACCOUNT_ID: string;
		R2_BUCKET_NAME: string;
		TEST_RESET_TOKEN: string;
		/** Optional. Raises GitHub API rate limits when set (`wrangler secret put GITHUB_TOKEN`). */
		GITHUB_TOKEN?: string;
	}
}
